# Exercise on Functions

## Task 1: Unit Conversion Program

In [ ]:
def convert_units():
    """
    Converts between different units of measurement (Length, Weight, Volume).
    """
    conversions = {
        "length": {"m_to_ft": 3.28084, "ft_to_m": 0.3048},
        "weight": {"kg_to_lbs": 2.20462, "lbs_to_kg": 0.453592},
        "volume": {"L_to_gal": 0.264172, "gal_to_L": 3.78541}
    }

    try:
        conv_type = input("Choose conversion type (length/weight/volume): ").strip().lower()
        if conv_type not in conversions:
            raise ValueError("Invalid conversion type!")

        value = float(input("Enter the value to convert: "))

        print("Choose conversion:")
        for key in conversions[conv_type]:
            print(key.replace("_", " to "))

        conv_choice = input("Enter conversion choice: ").strip().replace(" to ", "_")
        if conv_choice not in conversions[conv_type]:
            raise ValueError("Invalid conversion choice!")

        result = value * conversions[conv_type][conv_choice]
        print(f"Converted value: {result}")

    except ValueError as e:
        print(f"Error: {e}")

convert_units()

KeyboardInterrupt: Interrupted by user

## Task 2: Mathematical Operations on a List

In [ ]:
def sum_numbers(lst):
    """Returns the sum of the list."""
    return sum(lst)

def avg_numbers(lst):
    """Returns the average of the list."""
    return sum(lst) / len(lst) if lst else 0

def max_number(lst):
    """Returns the maximum number in the list."""
    return max(lst)

def min_number(lst):
    """Returns the minimum number in the list."""
    return min(lst)

def list_operations():
    """Prompts the user for list operations."""
    try:
        numbers = list(map(float, input("Enter numbers separated by space: ").split()))
        operation = input("Choose operation (sum/average/max/min): ").strip().lower()

        operations = {
            "sum": sum_numbers,
            "average": avg_numbers,
            "max": max_number,
            "min": min_number
        }

        if operation not in operations:
            raise ValueError("Invalid operation!")

        print(f"Result: {operations[operation](numbers)}")

    except ValueError as e:
        print(f"Error: {e}")

list_operations()

Enter numbers separated by space: 2 3 4
Choose operation (sum/average/max/min): 2 5 6 7
Error: Invalid operation!


# Exercise on List Manipulation

## Task 3: List Manipulation Functions

In [ ]:
# 1. Extract Every Other Element
def extract_every_other(lst):
    return lst[::2]

# 2. Slice a Sublist:
def get_sublist(lst, start, end):
    return lst[start:end+1]

# 3. Reverse a List Using Slicing
def reverse_list(lst):
    return lst[::-1]

# 4. Remove the First and Last Elements
def remove_first_last(lst):
    return lst[1:-1]

# 5. Get the First n Elements
def get_first_n(lst, n):
    return lst[:n]

# 6. Extract Elements from the End
def get_last_n(lst, n):
    return lst[-n:]

# 7. Extract Elements in Reverse Order:
def reverse_skip(lst):
    return lst[-2::-2]

In [ ]:
# Example Inputs and Outputs
sample_list_1 = [1, 2, 3, 4, 5, 6]
sample_list_2 = [1, 2, 3, 4, 5]

print("Extract Every Other:", extract_every_other(sample_list_1))
print("Slice a Sublist:", get_sublist(sample_list_1, 2, 4))
print("Reverse a List:", reverse_list(sample_list_2))
print("Remove First and Last:", remove_first_last(sample_list_2))
print("Get First n Elements:", get_first_n(sample_list_2, 3))
print("Extract Elements from End:", get_last_n(sample_list_2, 2))
print("Extract Elements in Reverse Order:", reverse_skip(sample_list_1))

Extract Every Other: [1, 3, 5]
Slice a Sublist: [3, 4, 5]
Reverse a List: [5, 4, 3, 2, 1]
Remove First and Last: [2, 3, 4]
Get First n Elements: [1, 2, 3]
Extract Elements from End: [4, 5]
Extract Elements in Reverse Order: [5, 3, 1]


# Exercise on Nested list

## Task 4: Nested List Functions

In [ ]:
# 1. Flatten a Nested List
def flatten(lst):
    return [item for sublist in lst for item in (sublist if isinstance(sublist, list) else [sublist])]

# 2. Accessing Nested List Elements
def access_nested_element(lst, indices):
    element = lst
    for index in indices:
        element = element[index]
    return element

# 3. Sum of All Elements in a Nested List
def sum_nested(lst):
    if isinstance(lst, int):
        return lst
    return sum(sum_nested(item) for item in lst)

# 4. Remove Specific Element from a Nested List
def remove_element(lst, elem):
    return [[item for item in sublist if item != elem] for sublist in lst]

# 5. Find the Maximum Element in a Nested List

def find_max(lst):
    flat_list = deep_flatten(lst)
    return max(flat_list)

# 6. Count Occurrences of an Element in a Nested List
def count_occurrences(lst, elem):
    flat_list = flatten(lst)
    return flat_list.count(elem)

# 7. Flatten a List of Lists of Lists
def deep_flatten(lst):
    if not isinstance(lst, list):
        return [lst]
    result = []
    for item in lst:
        result.extend(deep_flatten(item))
    return result

# 8. Nested List Average
def average_nested(lst):
    flat_list = deep_flatten(lst)
    return sum(flat_list) / len(flat_list) if flat_list else 0

In [ ]:
# Example Inputs and Outputs
nested_list_1 = [[1, 2], [3, 4], [5]]
nested_list_2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
nested_list_3 = [[1, 2], [3, [4, 5]], 6]
nested_list_4 = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

element_to_remove = 2
indices_to_access = [1, 2]

print("Flatten:", flatten(nested_list_1))
print("Access Nested Element:", access_nested_element(nested_list_2, indices_to_access))
print("Sum of Nested List:", sum_nested(nested_list_3))
print("Remove Specific Element:", remove_element([[1, 2], [3, 2], [4, 5]], element_to_remove))
print("Find Max:", find_max(nested_list_3))
print("Count Occurrences:", count_occurrences([[1, 2], [2, 3], [2, 4]], element_to_remove))
print("Deep Flatten:", deep_flatten(nested_list_4))
print("Nested List Average:", average_nested([[1, 2], [3, 4], [5, 6]]))

Flatten: [1, 2, 3, 4, 5]
Access Nested Element: 6
Sum of Nested List: 21
Remove Specific Element: [[1], [3], [4, 5]]
Find Max: 6
Count Occurrences: 3
Deep Flatten: [1, 2, 3, 4, 5, 6, 7, 8]
Nested List Average: 3.5


# Basic Vector and Matrix Operation with Numpy

## Problem - 1: Array Creation

In [ ]:
import numpy as np

# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("Empty Array:\n", empty_array)

# 2. Initialize an all-one array with size 4x2
ones_array = np.ones((4, 2))
print("\nAll Ones Array:\n", ones_array)

# 3. Return a new array of given shape and type, filled with fill value
fill_value = 7
filled_array = np.full((3, 3), fill_value)
print("\nFilled Array:\n", filled_array)

# 4. Return a new array of zeros with the same shape and type as a given array
reference_array = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_array = np.zeros_like(reference_array)
print("\nZeros Like Array:\n", zeros_like_array)

# 5. Return a new array of ones with the same shape and type as a given array
ones_like_array = np.ones_like(reference_array)
print("\nOnes Like Array:\n", ones_like_array)

# 6. Convert an existing list to a numpy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\nConverted NumPy Array:\n", numpy_array)

Empty Array:
 [[2.31621285e-316 0.00000000e+000]
 [1.55765441e-307 1.39080273e-308]]

All Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Filled Array:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros Like Array:
 [[0 0 0]
 [0 0 0]]

Ones Like Array:
 [[1 1 1]
 [1 1 1]]

Converted NumPy Array:
 [1 2 3 4]


## Problem - 2: Array Manipulation: Numerical Ranges and Array indexing

In [ ]:
def flatten(lst):
    return [item for sublist in lst for item in (sublist if isinstance(sublist, list) else [sublist])]

def access_nested_element(lst, indices):
    element = lst
    for index in indices:
        element = element[index]
    return element

def sum_nested(lst):
    if isinstance(lst, int):
        return lst
    return sum(sum_nested(item) for item in lst)

def remove_element(lst, elem):
    return [[item for item in sublist if item != elem] for sublist in lst]

def deep_flatten(lst):
    if not isinstance(lst, list):
        return [lst]
    result = []
    for item in lst:
        result.extend(deep_flatten(item))
    return result

def find_max(lst):
    flat_list = deep_flatten(lst)
    return max(flat_list)

def count_occurrences(lst, elem):
    flat_list = flatten(lst)
    return flat_list.count(elem)

def average_nested(lst):
    flat_list = deep_flatten(lst)
    return sum(flat_list) / len(flat_list) if flat_list else 0

# Example Inputs and Outputs
nested_list_1 = [[1, 2], [3, 4], [5]]
nested_list_2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
nested_list_3 = [[1, 2], [3, [4, 5]], 6]
nested_list_4 = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

element_to_remove = 2
indices_to_access = [1, 2]

print("Flatten:", flatten(nested_list_1))
print("Access Nested Element:", access_nested_element(nested_list_2, indices_to_access))
print("Sum of Nested List:", sum_nested(nested_list_3))
print("Remove Specific Element:", remove_element([[1, 2], [3, 2], [4, 5]], element_to_remove))
print("Find Max:", find_max(nested_list_3))
print("Count Occurrences:", count_occurrences([[1, 2], [2, 3], [2, 4]], element_to_remove))
print("Deep Flatten:", deep_flatten(nested_list_4))
print("Nested List Average:", average_nested([[1, 2], [3, 4], [5, 6]]))

# Array Manipulation: Numerical Ranges and Array Indexing
print("Array from 10 to 49:", np.arange(10, 50))
print("3x3 Matrix with values 0 to 8:", np.arange(9).reshape(3, 3))
print("3x3 Identity Matrix:", np.eye(3))

random_array = np.random.random(30)
print("Mean of Random Array:", random_array.mean())

random_matrix = np.random.random((10, 10))
print("Min and Max of 10x10 Random Matrix:", random_matrix.min(), random_matrix.max())

zero_array = np.zeros(10)
zero_array[4] = 1
print("Zero array with 5th element as 1:", zero_array)

arr = np.array([1, 2, 0, 0, 4, 0])
print("Reversed Array:", arr[::-1])

border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("2D Array with 1 border and 0 inside:", border_array)

checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("8x8 Checkerboard Pattern:", checkerboard)

Flatten: [1, 2, 3, 4, 5]
Access Nested Element: 6
Sum of Nested List: 21
Remove Specific Element: [[1], [3], [4, 5]]
Find Max: 6
Count Occurrences: 3
Deep Flatten: [1, 2, 3, 4, 5, 6, 7, 8]
Nested List Average: 3.5
Array from 10 to 49: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
3x3 Matrix with values 0 to 8: [[0 1 2]
 [3 4 5]
 [6 7 8]]
3x3 Identity Matrix: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Mean of Random Array: 0.5219086275716472
Min and Max of 10x10 Random Matrix: 0.008378844170815691 0.9526581768941054
Zero array with 5th element as 1: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
Reversed Array: [0 4 0 0 2 1]
2D Array with 1 border and 0 inside: [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
8x8 Checkerboard Pattern: [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 

## Problem - 3: Array Operations

In [ ]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

print("Addition of x and y:", x + y)
print("Subtraction of x and y:", x - y)
print("Multiplication of x by 2:", x * 2)
print("Square of x:", np.square(x))
print("Dot product of v and w:", np.dot(v, w))
print("Dot product of x and v:", np.dot(x, v))
print("Dot product of x and y:", np.dot(x, y))
print("Concatenation of x and y along rows:", np.concatenate((x, y), axis=0))
print("Concatenation of v and w along columns:", np.column_stack((v, w)))

try:
    print("Concatenation of x and v:", np.concatenate((x, v), axis=0))
except ValueError as e:
    print("Error in concatenating x and v:", e)

Addition of x and y: [[ 6  8]
 [10 13]]
Subtraction of x and y: [[-4 -4]
 [-4 -3]]
Multiplication of x by 2: [[ 2  4]
 [ 6 10]]
Square of x: [[ 1  4]
 [ 9 25]]
Dot product of v and w: 219
Dot product of x and v: [29 77]
Dot product of x and y: [[19 22]
 [50 58]]
Concatenation of x and y along rows: [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenation of v and w along columns: [[ 9 11]
 [10 12]]
Error in concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


## Problem - 4: Matrix Operations

In [ ]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# Proving A.A⁻¹ = I
A_inv = np.linalg.inv(A)
identity_matrix = np.dot(A, A_inv)
print("A * A⁻¹:", identity_matrix)

# Proving AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB:", AB)
print("BA:", BA)
print("AB == BA:", np.array_equal(AB, BA))

# Proving (AB)^T = B^T * A^T
AB_T = AB.T
BT_AT = np.dot(B.T, A.T)
print("(AB)^T:", AB_T)
print("B^T * A^T:", BT_AT)
print("(AB)^T == B^T * A^T:", np.array_equal(AB_T, BT_AT))

# Solving the system of linear equations
coeff_matrix = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
const_matrix = np.array([-1, -3, 9])
solution = np.linalg.solve(coeff_matrix, const_matrix)
print("Solution to the system of equations:", solution)


A * A⁻¹: [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
AB: [[23 13]
 [51 29]]
BA: [[36 44]
 [13 16]]
AB == BA: False
(AB)^T: [[23 51]
 [13 29]]
B^T * A^T: [[23 51]
 [13 29]]
(AB)^T == B^T * A^T: True
Solution to the system of equations: [ 2.  1. -2.]


## Experiment: How Fast is Numpy?

In [ ]:
import time

def flatten(lst):
    return [item for sublist in lst for item in (sublist if isinstance(sublist, list) else [sublist])]

def access_nested_element(lst, indices):
    element = lst
    for index in indices:
        element = element[index]
    return element

def sum_nested(lst):
    if isinstance(lst, int):
        return lst
    return sum(sum_nested(item) for item in lst)

def remove_element(lst, elem):
    return [[item for item in sublist if item != elem] for sublist in lst]

def deep_flatten(lst):
    if not isinstance(lst, list):
        return [lst]
    result = []
    for item in lst:
        result.extend(deep_flatten(item))
    return result

def find_max(lst):
    flat_list = deep_flatten(lst)
    return max(flat_list)

def count_occurrences(lst, elem):
    flat_list = flatten(lst)
    return flat_list.count(elem)

def average_nested(lst):
    flat_list = deep_flatten(lst)
    return sum(flat_list) / len(flat_list) if flat_list else 0

# Experiment: How Fast is Numpy?
size = 1000000
list1 = list(range(size))
list2 = list(range(size))
numpy_arr1 = np.arange(size)
numpy_arr2 = np.arange(size)

# Element-wise Addition
start_time = time.time()
list_addition = [list1[i] + list2[i] for i in range(size)]
print("Time taken for addition using Python lists:", time.time() - start_time)

start_time = time.time()
numpy_addition = numpy_arr1 + numpy_arr2
print("Time taken for addition using NumPy:", time.time() - start_time)

# Element-wise Multiplication
start_time = time.time()
list_multiplication = [list1[i] * list2[i] for i in range(size)]
print("Time taken for multiplication using Python lists:", time.time() - start_time)

start_time = time.time()
numpy_multiplication = numpy_arr1 * numpy_arr2
print("Time taken for multiplication using NumPy:", time.time() - start_time)

# Dot Product
start_time = time.time()
list_dot_product = sum(list1[i] * list2[i] for i in range(size))
print("Time taken for dot product using Python lists:", time.time() - start_time)

start_time = time.time()
numpy_dot_product = np.dot(numpy_arr1, numpy_arr2)
print("Time taken for dot product using NumPy:", time.time() - start_time)

# Matrix Multiplication
size_matrix = 1000
matrix1 = [[i * j for j in range(size_matrix)] for i in range(size_matrix)]
matrix2 = [[i + j for j in range(size_matrix)] for i in range(size_matrix)]
numpy_matrix1 = np.array(matrix1)
numpy_matrix2 = np.array(matrix2)

start_time = time.time()
result_matrix = [[sum(a * b for a, b in zip(row, col)) for col in zip(*matrix2)] for row in matrix1]
print("Time taken for matrix multiplication using Python lists:", time.time() - start_time)

start_time = time.time()
numpy_matrix_multiplication = np.dot(numpy_matrix1, numpy_matrix2)
print("Time taken for matrix multiplication using NumPy:", time.time() - start_time)

Time taken for addition using Python lists: 0.06804037094116211
Time taken for addition using NumPy: 0.004288911819458008
Time taken for multiplication using Python lists: 0.07299184799194336
Time taken for multiplication using NumPy: 0.0038313865661621094
Time taken for dot product using Python lists: 0.07680678367614746
Time taken for dot product using NumPy: 0.0015401840209960938
Time taken for matrix multiplication using Python lists: 152.7419991493225
Time taken for matrix multiplication using NumPy: 1.0644035339355469
